### ISSUE TITLE
Food Barcode Scanner

### ISSUE THREAD

**Issue by ZzBobTheBuilderzZ** [SeanGBX/OOPP-Project#10]
Scanning a food bar code will give us its nutritional information (such as calories) and expiry date.

**Comment by ZzBobTheBuilderzZ** [comment]
Acceptance Criteria
1) Able to read the bar code.
2) Provide the nutritional information and expiry date.

**Comment by SeanGBX** [comment]
This issue was moved to SeanGBX/OOPPProject#10
