### ISSUE TITLE
Food Database

### ISSUE THREAD

**Issue by ZzBobTheBuilderzZ** [SeanGBX/OOPP-Project#11]
A database of the amount of calories of each food item. This is for us to retrieve this data and display the food's calories when a food item is selected.

**Comment by ZzBobTheBuilderzZ** [comment]
Acceptance Criteria
1) Create a food data base
2) Link the database with other pages

**Comment by SeanGBX** [comment]
This issue was moved to SeanGBX/OOPPProject#11
